### ISSUE TITLE
IND UAV operator has BLU UAV terminal

### ISSUE THREAD

**Issue by JesseHaycraft** [tanaaKa/CMF#14]
In CMF 4.5, the Independent faction UAV operator has the Blufor UAV terminal which prevents him from using it.

**Comment by tanaaKa** [comment]
This is based on gearscript.

Line 188 in f/loadouts/gearscript.hpp:

> class soldier_UAV_F: Soldier_F {
>   backpack[] = {"I_UAV_01_backpack_F"};
>   linkedItems[] += {"I_uavterminal"};
>   items[] += {RADIO_MR};
> };


For redundancy, I've updated baseTemplate_EAST and basetemplate_IND to avoid this in the future. A function will have to be written to assign the proper UAV gear depending on side that the gearscript is used on.

Fixed in https://github.com/tanaaKa/CMF/commit/dbd621cbe72b169229424bcf5e1bf645513cb8e6
